### ISSUE TITLE
Refactor .gitops.config.yaml

### ISSUE THREAD

**Issue by niiku** [baloise/gitopscli#105]
Currently the `.gitops.config.yaml` file looks like this:
```yaml
deploymentConfig:
  # The organisation name of your deployment repo
  org: deployments
  # The repostiory name of your deployment repo
  repository: deployment-config-repo
  # The name of the application (name of the folder in `.preview-templates`)
  applicationName: app-xy

previewConfig:
  route:
    host:
      # Your router host
      # {SHA256_8CHAR_BRANCH_HASH} gets replaced by a shortened hash of your preview_id
      template: app.xy-{SHA256_8CHAR_BRANCH_HASH}.example.tld
  replace:
    # Paths that should be replaced in the `values.yaml`
    - path: image.tag
      variable: GIT_COMMIT # this is the git hash of your app repo
    - path: route.host
      variable: ROUTE_HOST # this is the resolved host.template from above
```
Proposed changes:
* Add an `apiVersion` field so we can introduce breaking changes (at least required for the proposed changes)
* Rename `deploymentConfig` to `configRepository` or `configRepo`
* Drop `previewConfig.route` as it is OpenShift specific and not flexible
* Add templating support to `previewConfig.replace[].variable` to make the template feature which currently lives under `previewConfig.route.host.template` available in a more flexible manner. Maybe we should drop `previewConfig.replace[].variable` as well and name it `previewConfig.replace[].value` with "${VAR}" support .
* Rename the available `SHA256_8CHAR_BRANCH_HASH` variable to `BRANCH_NAME_SHA_SHORT` or similar - the current name is not rememberable.

**Comment by christiansiegel** [comment]
+1 for the proposed changes
- I would use e.g. `PREVIEW_ID` instead of `SHA256_8CHAR_BRANCH_HASH` because for `create-preview` you can already choose  something different from the branch as id 
- The `previewConfig.route.host.template` is currently also used as link in the PR comment. If we drop this and move the templating into the replace mechanism, we need an alternative source for that. Maybe we can just ask for the path to the final url in the chart and read it from there after the replacement (`url: myapp.network.http.ingress.host`)?
- Maybe we should also add the possibility to replace in files other than `values.yaml`? This would solve #74

**Comment by niiku** [comment]
Calling it `PREVIEW_ID` would be fine for me as well. Maybe we can discuss again about more speaking preview URLs?

Regarding `previewConfig.route.host` we could simply drop the `route` part (e.g. `previewConfig.host`). 

To add support for non Helm based deployments we could add something like this:
```yaml
previewConfig:
  templateType: plain # could be changed to helm

replace:
  - path: spec.template.spec.containers[0].image
    value: registry.example.tld/org/myimage:${GIT_COMMIT}
    file: deployment.yaml # in case of helm would default to values.yaml
```

Another idea which came to my mind restructuring the `.gitopc.config.yaml` like this
```
apiVersion: v1
applicationName: my-cool-app
previewConfig:
  templateType: helm
  host: ${PREVIEW_ID}-preview.apps.example.tld
  # optional section
  templateSource:
    repository: https://github.com/org/repo.git # would default to `templateTarget.repository`
    path: .chart/ # would default to `.preview-templates/${applicationName}`
  templateTarget:
    repository: https://github.com/org/config-repo.git
  replace: 
    - path: app.image.tag
      value: ${GIT_COMMIT}
```

This would open the possibility to chose where the template is taken from. So e.g. I can put the template for the preview environments to the application repository and when I create a preview the template is taken from the corresponding branch. Any thoughts?

**Comment by christiansiegel** [comment]
> Calling it PREVIEW_ID would be fine for me as well. Maybe we can discuss again about more speaking preview URLs?

Good point. We could use the branch name (or preview id in case of `create-preview`) and remove all special chars. Since we have to truncate (after 63?) chars, it is possible to have naming conflicts (e.g. `my-long-branch-name-...-ending-1` + `my-long-branch-name-...-ending-2` -> `my-app-my-long-branch-name-...-en-preview`). I guess we could replace the last e.g. 6 chars of a truncated name with its hash (`my-app-my-long-branch-name-..-af46gf-preview`) or something to prevent that...

> Another idea which came to my mind restructuring the .gitopc.config.yaml like this

I like that idea! Regarding the support for different templating system: Why not be even more explicit and always specify the file name? While this adds 2 more lines for Helm based projects it also reduces the "magic" behind the scenes:
```yaml
apiVersion: v1
applicationName: my-cool-app
previewConfig:
  host: ${PREVIEW_ID}-preview.apps.example.tld
  # optional section
  templateSource:
    repository: https://github.com/org/repo.git # would default to `templateTarget.repository`
    path: .chart/ # would default to `.preview-templates/${applicationName}`
  templateTarget:
    repository: https://github.com/org/config-repo.git
  replace: 
    values.yaml:
    - path: app.image.tag
      value: ${GIT_COMMIT}
    - path: app.network.http.ingress.host
      value: ${HOST}
    Chart.yaml:
    - path: name
      value: ${PREVIEW_NAMESPACE}
    README.md: # just an idea: "Preview for branch BRANCH: HOST"
    - regex: BRANCH
      value: ${PREVIEW_ID}
    - regex: HOST
      value: ${HOST}
```

**Comment by niiku** [comment]
I like the idea of combining the branchname and hash - maybe fewer hash chars would be sufficient.

Yeah we can drop the Helm specific part. I just thought a bit about your `replace` proposal - first I wasn't sure if using file names as key is a good idea - but it makes it actually easy readable - and there's also almost no limitation to keys in YAML. So the replacements to the file are kept together in a nice way. 

Maybe we should rename `previewConfig.replace{}.path` to something like `yamlPath` to make it more clear what kind of path that is.

**Comment by niiku** [comment]
Just a minor thought:
```yaml
previewConfig:
  host: ${PREVIEW_ID}-preview.apps.example.tld
  templateSource:
    repository: https://github.com/org/repo.git 
    path: .chart/ 
    branch: master # if not set defaults to feature branch 
  templateTarget:
    repository: https://github.com/org/config-repo.git
    branch: main # defaults to master
```

**Comment by joachimprinzbach** [comment]
Can we already agree on the target design for api version 2?

**Comment by joachimprinzbach** [comment]
```yaml
apiVersion: v1
applicationName: my-cool-app
previewConfig:
  host: ${PREVIEW_ID}-preview.apps.example.tld
  # optional section
  templateSource:
    repository: https://github.com/org/repo.git # would default to `templateTarget.repository`
    path: .chart/ # would default to `.preview-templates/${applicationName}`
    branch: master # if not set defaults to feature branch - if templateSource is missing defaults to `templateTarget.branch`
  templateTarget:
    repository: https://github.com/org/config-repo.git
    branch: main # defaults to master
  replace: 
    values.yaml:
    - path: app.image.tag
      value: ${GIT_COMMIT}
    - path: app.network.http.ingress.host
      value: ${HOST}
    Chart.yaml:
    - path: name
      value: ${PREVIEW_NAMESPACE}
    README.md: # just an idea: "Preview for branch BRANCH: HOST"
    - regex: BRANCH
      value: ${PREVIEW_ID}
    - regex: HOST
      value: ${HOST}
```

**Comment by joachimprinzbach** [comment]
> Maybe we should rename previewConfig.replace{}.path to something like yamlPath to make it more clear what kind of path that is.
I would rather call it `yamlProperty` or `yamlNode`

**Comment by joachimprinzbach** [comment]
Still trying to find a better name for `templateTarget`. Any ideas?

**Comment by joachimprinzbach** [comment]
Regarding additional replace values (like the regex stuff for the README.md)
Those are not breaking changes, therefore could be easily added without changing the API version. I would add them later if needed.

**Comment by joachimprinzbach** [comment]
> > Maybe we should rename previewConfig.replace{}.path to something like yamlPath to make it more clear what kind of path that is.
> 
> I would rather call it `yamlProperty` or `yamlNode`

Discussed with @niiku: yamPath is fine :)

**Comment by joachimprinzbach** [comment]
> Still trying to find a better name for `templateTarget`. Any ideas?

`templateSource` -> `template`
`templateTarget` -> `target` | `previewConfig`

**Comment by joachimprinzbach** [comment]
```yaml
apiVersion: v1
applicationName: my-cool-app
previewConfig:
  host: ${PREVIEW_ID}-preview.apps.example.tld
  # optional section
  template:
    repository: https://github.com/org/repo.git # would default to `templateTarget.repository`
    path: .chart/ # would default to `.preview-templates/${applicationName}`
    branch: master # if not set defaults to feature branch - if templateSource is missing defaults to `templateTarget.branch`
  target:
    repository: https://github.com/org/config-repo.git
    branch: main # defaults to master
  replace: 
    values.yaml:
    - path: app.image.tag
      value: ${GIT_COMMIT}
    - path: app.network.http.ingress.host
      value: ${HOST}
    Chart.yaml:
    - path: name
      value: ${PREVIEW_NAMESPACE}
```

**Comment by christiansiegel** [comment]
> > Still trying to find a better name for `templateTarget`. Any ideas?
> 
> `templateSource` -> `template`
> `templateTarget` -> `target` | `previewConfig`

`template` and `target` are fine for me.

Minor thing I noticed now: the `previewConfig.target.branch` should default to the *default branch* of the repository instead of `master` (see also #115).

Do we also want to make the preview namespace/folder configurable? Just to uncover another magic part:
```yaml
previewConfig:
  host: ${PREVIEW_ID}-preview.apps.example.tld
  namespace: ${PREVIEW_ID}-dev # defaults to ${PREVIEW_ID}-preview
```

For the `PREVIEW_ID` I'd suppose something like that to make it more readable:
```python
# pseudo
raw_preview_id = branch or user defined preview_id in case of create-preview
sanitzed_preview_id = sanitize(raw_preview_id) # remove everything that cannot be used in namespace or folder name
preview_id = sanitzed_preview_id[:34] + sha256(raw_preview_id)[:6] # truncate preview id after 34 chars + append short hash
```
This would mean the `PREVIEW_ID` has max 40 chars -> the user can add 23 chars in the `previewConfig.namespace`

**Comment by joachimprinzbach** [comment]
Regarding the default branch: 
Great idea - but would imply API calls, right? 

The configurable preview folder name / namespace is also a great idea. 
Should me move the property to target?

Still struggling with those 63 chars, not sure what is counted in (host / path). Maybe we should try it out.

**Comment by christiansiegel** [comment]
> Regarding the default branch:
> Great idea - but would imply API calls, right?

Not necessarily. When cloning the repo I think you should always get the default branch. Currently we explicitly checkout `master` after cloning.

> The configurable preview folder name / namespace is also a great idea.
> Should me move the property to target?

Ah, yes. Makes more sense.

> Still struggling with those 63 chars, not sure what is counted in (host / path). Maybe we should try it out.

It's a restriction of the project/namespace name (https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/projects_and_users.html#:~:text=63). I don't think the host url is restricted..?


updated proposal:
```yaml
apiVersion: v1
applicationName: my-cool-app
previewConfig:
  host: ${PREVIEW_ID}-preview.apps.example.tld
  template:  # optional section
    repository: https://github.com/org/repo.git # would default to `target.repository`
    path: .chart/ # would default to `.preview-templates/${applicationName}`
    branch: master # if not set defaults to feature branch - if templateSource is missing defaults to `target.branch`
  target:
    repository: https://github.com/org/config-repo.git
    branch: main # defaults to repo's default branch (usually master or main)
    namespace: ${PREVIEW_ID}-dev # defaults to `${PREVIEW_ID}-preview` (PREVIEW_ID has max length TBD. Make sure not to exceed 63 chars total)
  replace: 
    values.yaml:
    - path: app.image.tag
      value: ${GIT_COMMIT}
    - path: app.network.http.ingress.host
      value: ${HOST}
    Chart.yaml:
    - path: name
      value: ${PREVIEW_NAMESPACE}
```
