### ISSUE TITLE
[deploy]: not respecting special characters

### ISSUE THREAD

**Issue by Ahmadre** [baloise/gitopscli#152]
The deploy command is not respecting the official YAML-Notation of special characters.

See: https://stackoverflow.com/a/22235064/5535773

We're not able to deploy (espacially `upgrade --install`) our configmap which includes values like:

- `test://user:pw@domain.com:PORT` or
- `http://service`

To be able to apply dynamic configmaps here's an example like helm v3 is suggesting:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
{{- with .Values.config.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
```

If you try run the deploy command it overrides all double quoted config values from:

`"test://user:pw@domain.com:PORT"` -> `test://user:pw@domain.com:PORT`

gitopscli should check if yaml special characters are available and then decide to take the quoted or not quoted value.

**Comment by Ahmadre** [comment]
I got a solution and workaround:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.config.data }}
  {{ nindent 2 $key }}: {{ quote $value }}
{{- end }}
```

But maybe this issue is anyway important, if you think so.
