### ISSUE TITLE
Nested json inside yaml

### ISSUE THREAD

**Issue by epanoff** [baloise/gitopscli#196]
Sometimes, I need to update the dictionary with GitOpsCLI. For example, I need to update variables in the following service code:

```
service:
  env:
    variables:
      LOGSTASH_HOST: "logstash"
      ELASTIC_APM_ENABLED: "false"
```

To do this, I run the command:

`gitopscli deploy --file env/prod-values.yaml --single-commit --username values_updater --password password --git-provider GITLAB --repository-name repo --organisation org --git-provider-url https://gitlab --create-pr --values '{service.env.variables: {"LOGSTASH_HOST": "logstash", "ELASTIC_APM_ENABLED": "true"}}'`

After executing this command, I get the following result:

bash

```
service:
  env:
    variables: {"LOGSTASH_HOST": "logstash", "ELASTIC_APM_ENABLED": "true"}
```

This method works, but it is not very pretty. it would be nice to get clean yaml.
